### ISSUE TITLE
add-apt-repository -y ppa:marlam/gta, I need help😭

### ISSUE THREAD

**Issue by SuInLearning** [marlam/gta-mirror#1]
## Please check that the PPA name or format is correct.
# I would like to ask how to solve this problem😭😭😭

**Comment by marlam** [comment]
That ppa does not exist anymore, it was deleted in 2017.
Where did you come across instructions to use this?
Maybe I can help to find an alternative, or maybe (most likely) you don't actually need that ppa.

**Comment by SuInLearning** [comment]
Firstly, thank you very much for your reply!
hllps://github.com/geometalab/docker-gdal-with-FileGDB
This is a repository from eight years ago, where line 210 in its Makefile uses "add-opt-repository -y ppa:malam/gta", which is where the "Please check that the PPA name or format is correct" error appears.
The appearance of "marlam-gta-trust. list" on line 179, "libgta-dev" on line 33, and "-- with-gta" on line 83 may all have a dependency on the operation of adding ppa on line 210.
I want to know: 
1. Is there an **alternative ppa**
2. If not, is there a suitable software repository that can be added to the system's **sources.list** file, similar to this format: 
deb http://ppa.launchpad.net/dr-akulavich/lighttable/ubuntu YOU_ UBUNTU_ VERSION_ HERE main
deb-src http://ppa.launchpad.net/dr-akulavich/lighttable/ubuntu YOU_ UBUNTU_ VERSION_ HERE main
3. Other potentially helpful information
Looking forward to your reply very much

**Comment by SuInLearning** [comment]
> That ppa does not exist anymore, it was deleted in 2017. Where did you come across instructions to use this? Maybe I can help to find an alternative, or maybe (most likely) you don't actually need that ppa.

Firstly, thank you very much for your reply!

hllps://github.com/geometalab/docker-gdal-with-FileGDB
This is a repository from eight years ago, where line 210 in its Makefile uses "add-opt-repository -y ppa:malam/gta", which is where the "Please check that the PPA name or format is correct" error appears.

The appearance of "marlam-gta-trust. list" on line 179, "libgta-dev" on line 33, and "-- with-gta" on line 83 may all have a dependency on the operation of adding ppa on line 210.

I want to know:
1. Is there an alternative ppa
2. If not, is there a suitable software repository that can be added to the system's sources.list file, similar to this format:
deb http://ppa.launchpad.net/dr-akulavich/lighttable/ubuntu YOU_ UBUNTU_ VERSION_ HERE main
deb-src http://ppa.launchpad.net/dr-akulavich/lighttable/ubuntu YOU_ UBUNTU_ VERSION_ HERE main
3. Other potentially helpful information

Looking forward to your reply very much

**Comment by marlam** [comment]
There is no alternative ppa and in fact the libgta library is [deprecated now](https://marlam.de/gta/news/gta-superseded-by-tad/).

I'm pretty sure you can just delete every reference to gta; it is most likely not needed for your purposes. The main benefit of the gta file format at its time was that you can have an arbitrary number of channels with arbitrary data types, in particular an unlimited number of floating point channels. If you don't need that feature, you don't need gta.

Also, current GDAL has builtin [OpenFileGDB](https://gdal.org/drivers/vector/openfilegdb.html#vector-openfilegdb) support; are you sure you need the proprietary plugin in a container that is 8 years old? Alternatively, you can build current GDAL with the current ESRI FileGDB SDK.

**Comment by SuInLearning** [comment]
Received. Thank you for your reply. It was helpful
